archs = {
    "ogbn_withLabel": [['PF', 'PAPP', 'PFPF', 'PPPF', 'PAIAP', 'PAPFP', 'PFPPP', 'PPAPF', 'PAIAPF', 'PAIAPP', 'PAPAPF', 'PAPPPF', 'PFPPAP', 'PFPPPF', 'PPAPPF', 'PAIAPAP', 'PAPAPPP', 'PAPPPAP', 'PFPPPPP', 'PPAPPPF', 'PPPAPAP', 'PPPAPPF', 'PPPPAPF'], ['PP', 'PAP', 'PPAP', 'PPPP', 'PAIAP', 'PFPAP', 'PPAPP']],

    "ogbn_withLabel2": [['PF', 'PP', 'PAP', 'PAPF', 'PPAP', 'PPPP', 'PAIAP', 'PFPPF', 'PPAPF', 'PAIAPP', 'PAPPFP', 'PFPFPF', 'PPPAPF', 'PPPPAP', 'PAPAPAP', 'PAPPPPP', 'PFPAPFP', 'PPAPPPA', 'PPPAPPF', 'PPPPAPP'], ['PP', 'PAP', 'PFP', 'PPP', 'PPAP', 'PPPP', 'PAIAP', 'PAPAP', 'PPAPP', 'PPPAP']],
    
    "ogbn_withLabel3": [['PF', 'PFPF', 'PPPF', 'PFPAP', 'PPPFP', 'PAPPAP', 'PFPAPF', 'PPAPAP', 'PPAPFP', 'PPAPPF', 'PAIAIAP', 'PAIAPPF', 'PAPAIAP', 'PAPPPAP', 'PAPPPPF', 'PFPAPAP', 'PFPAPPF', 'PFPPPAP', 'PFPPPPP', 'PPAPFPF', 'PPAPPAP', 'PPPAPAP', 'PPPAPPF', 'PPPPAPF'], ['PAP', 'PFP', 'PAPP', 'PPAP', 'PAPAP', 'PPPPP']],

    "ogbn_withLabel4": [['P','PF', 'PAPP', 'PFPF', 'PPPF', 'PAIAP', 'PAPFP', 'PFPAP', 'PFPPP', 'PPAPF', 'PPPFP', 'PAIAPF', 'PAIAPP', 'PAPAPF', 'PAPPAP', 'PAPPPF', 'PFPAPF', 'PFPPAP', 'PFPPPF', 'PPAPAP', 'PPAPFP', 'PPAPPF', 'PAIAIAP', 'PAIAPAP', 'PAIAPPF', 'PAPAIAP', 'PAPAPPP', 'PAPPPAP', 'PAPPPPF', 'PFPAPAP', 'PFPAPPF', 'PFPPPAP', 'PFPPPPP', 'PPAPFPF', 'PPAPPAP', 'PPAPPPF', 'PPPAPAP', 'PPPAPPF', 'PPPPAPF'],['PP', 'PAP', 'PFP', 'PAPP','PPAP', 'PPPP', 'PAIAP', 'PFPAP', 'PPAPP','PAPAP', 'PPPPP']],

    "ogbn_withLabel5": [['PF', 'PP', 'PAI', 'PAP', 'PFP', 'PPA', 'PPF', 'PPP', 'PAPP', 'PFPF', 'PPPF', 'PAIAP', 'PAPFP', 'PFPPP', 'PPAPF', 'PAIAPF', 'PAIAPP', 'PAPAPF', 'PAPPPF', 'PFPPAP', 'PFPPPF', 'PPAPPF', 'PAIAPAP', 'PAPAPPP', 'PAPPPAP', 'PFPPPPP', 'PPAPPPF', 'PPPAPAP', 'PPPAPPF', 'PPPPAPF'], ['PP', 'PAP', 'PPAP', 'PPPP', 'PAIAP', 'PFPAP', 'PPAPP']],

    "ogbn_withLabel6":[['PF', 'PFP', 'PFPF', 'PAPAP', 'PAPPF', 'PFPAP', 'PFPPP', 'PPPAP', 'PAIAPP', 'PAPAPP', 'PAPPAP', 'PAPPPF', 'PAPPPP', 'PFPAPF', 'PFPPPF', 'PPAPPF', 'PPAPPP', 'PPPPPF', 'PAIAIAP', 'PAPPPAP', 'PAPPPPF', 'PPPAPAP', 'PPPPAPF'], ['PP', 'PAP', 'PFP', 'PPAP', 'PAPAP', 'PPAPP', 'PPPPP']],
    
    "ogbn_withoutLabel": [['PF', 'PAPF', 'PFPP', 'PAPPP', 'PFPFP', 'PPAPP', 'PPPAP', 'PPPFP', 'PAIAPP', 'PAPAPF', 'PFPAPF', 'PFPPPF', 'PFPPPP', 'PPAPPF', 'PPPAPF', 'PPPPAP', 'PPPPPF', 'PAIAPAP', 'PAPAPAP', 'PAPAPPP', 'PAPPPAI', 'PAPPPPF', 'PAPPPPP', 'PFPAPAP', 'PFPPFPF', 'PFPPPPF', 'PPAPAPF', 'PPAPAPP', 'PPPAIAI', 'PPPAPPP'], []],
    
    "ogbn_withLabel_114514": [['PF', 'PAPP', 'PFPF', 'PPAP', 'PAIAP', 'PAPAP', 'PAPPF', 'PFPAP', 'PAPAPF', 'PFPPAP', 'PFPPPF', 'PPPPAP', 'PAIAIAP', 'PAIAPAP', 'PAIAPPP', 'PAPAIAP', 'PAPPAPF', 'PAPPPAP', 'PFPFPPP', 'PFPPAPF', 'PFPPAPP', 'PPAPAPP', 'PPPAPAP'], ['PP', 'PAPP', 'PPAP', 'PAPAP', 'PFPAP', 'PPAPP', 'PPPAP']],
    "ogbn_withLabel_3407": [['PF', 'PPPF', 'PAIAP', 'PAPAP', 'PFPAP', 'PFPPF', 'PAIAPF', 'PAPAPF', 'PAPAPP', 'PAPPPF', 'PAPPPP', 'PFPAPF', 'PFPPPF', 'PPAPAP', 'PPAPPF', 'PAIAPAI', 'PAIAPAP', 'PAPAPAP', 'PAPPAPF', 'PAPPPPP', 'PFPAPAP', 'PFPPPPF', 'PPPAPPF', 'PPPAPPP', 'PPPPAPP', 'PPPPPPP'], ['PAP', 'PFP', 'PPPP', 'PAPPP']],
    "ogbn_withLabel_bs5000": [['PF', 'PFP', 'PAPP', 'PFPP', 'PPAP', 'PFPPF', 'PPAPP', 'PAPAPF', 'PAPPPP', 'PFPAPF', 'PFPPPP', 'PPAPAP', 'PPPAPF', 'PPPPPP', 'PAIAIAP', 'PAIAPAP', 'PAIAPPF', 'PAPAPPP', 'PAPPPAP', 'PFPFPAP', 'PFPFPPF', 'PFPPAPP', 'PPPAPAP', 'PPPAPPP', 'PPPPFPP'], ['PAPP', 'PPAP', 'PPPP', 'PAPAP', 'PPPAP']],
    }
