_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 1
                - 5
                - 53
                - 55
                - 76
                - 77
            "2":
                - 1
                - 5
                - 53
                - 55
                - 76
                - 77
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.8.20
            "5": 0.19.11
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
amp:
    value: true
arch:
    value: ogbn_withLabel
att_drop:
    value: 0
batch_size:
    value: 10000
bns:
    value: true
cpu:
    value: false
dataset:
    value: ogbn-mag
dropout:
    value: 0.5
edge_mask_ratio:
    value: 0
emb_path:
    value: ../data/
embed_size:
    value: 256
eps:
    value: 0
eval_every:
    value: 1
extra_embedding:
    value: ""
gama:
    value: 5
gpu:
    value: 0
hidden:
    value: 512
identity:
    value: false
in_max_deg:
    value: null
input_drop:
    value: 0.1
label_bns:
    value: true
label_drop:
    value: 0
label_feats:
    value: true
lr:
    value: 0.003
mask_seed:
    value: 1
max_mask_deg:
    value: null
n_layers_2:
    value: 2
n_layers_3:
    value: 2
num_hops:
    value: 6
num_label_hops:
    value: 4
out_max_deg:
    value: null
patience:
    value: 50
reload:
    value: ""
residual:
    value: true
root:
    value: ../data/
run_name:
    value: ogbn_withLabel_run2_200
seed:
    value: 2
seeds:
    value:
        - 2
stages:
    value:
        - 200
        - 200
        - 200
        - 200
        - 200
        - 200
        - 200
start_stage:
    value: 0
threshold:
    value: 0.6
use_wandb:
    value: true
wandb_entity:
    value: null
wandb_project:
    value: LMSPS
weight_decay:
    value: 0
